-----Drop user ---------------------
--ALTER SESSION SET "_ORACLE_SCRIPT"=TRUE;
--drop USER C##Admin_QLNV_GROUP08 ;
--ALTER SESSION SET "_ORACLE_SCRIPT"=FALSE;
--/

BEGIN
    EXECUTE IMMEDIATE 'ALTER SESSION SET "_ORACLE_SCRIPT"=TRUE';
    EXECUTE IMMEDIATE 'revoke SYSDBA from ADMIN_GROUP8 CONTAINER = ALL';
     EXECUTE IMMEDIATE 'revoke DBA from ADMIN_GROUP8 CONTAINER = ALL';
    EXECUTE IMMEDIATE 'drop user ADMIN_GROUP8 CASCADE';
    EXECUTE IMMEDIATE 'ALTER SESSION SET "_ORACLE_SCRIPT"=FALSE';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -1917 THEN
         RAISE;
      END IF;
END;
/
---Tao user ADMIN quan ly HE THONG QLNV
ALTER SESSION SET "_ORACLE_SCRIPT"=TRUE;
CREATE USER ADMIN_GROUP8 IDENTIFIED BY ADMIN_GROUP8;
ALTER SESSION SET "_ORACLE_SCRIPT"=FALSE;


--Cap quota cho Admin_QLNV
ALTER USER ADMIN_GROUP8 QUOTA UNLIMITED ON USERS;


/
---Cap quyen
GRANT CONNECT TO ADMIN_GROUP8 WITH ADMIN OPTION;
GRANT CREATE SESSION TO ADMIN_GROUP8;
GRANT CREATE ANY CONTEXT TO ADMIN_GROUP8;
GRANT SYSDBA TO ADMIN_GROUP8 WITH ADMIN OPTION CONTAINER = ALL; 
GRANT DBA TO ADMIN_GROUP8 WITH ADMIN OPTION; 
GRANT ALL PRIVILEGES TO ADMIN_GROUP8;

-------------------------------------CAP QUYEN XEM BANG SYSTEM----------------------------------
--Cap quyen cho admin doc - xem user nao co trong he thong (HT tong)
GRANT SELECT ON DBA_SYS_PRIVS TO ADMIN_GROUP8; --Cap quyen doc tren bang DBA_SYS_PRIVS
GRANT SELECT ON DBA_TAB_PRIVS TO ADMIN_GROUP8; --Cap quyen doc tren bang DBA_TAB_PRIVS
GRANT SELECT ON DBA_ROLE_PRIVS TO ADMIN_GROUP8; --Cap quyen doc tren bang DBA_ROLE_PRIVS


--GRANT CREATE PUBLIC SYNONYM TO C##Admin_QLNV_GROUP08;
--Specify WITH ADMIN OPTION to enable the grantee to:
    --Grant the privilege or role to another user or role, unless the role is a GLOBAL role
    --Revoke the privilege or role from another user or role
    --Alter the privilege or role to change the authorization needed to access it
    --Drop the privilege or role
    --Grant the role to a program unit in the grantee's schema.

--> WITH ADMIN OPTION: CAP DOI VOI QUYEN HE THONG
--> WITH GRANT OPTION: CAP DOI VOI QUYEN OBJECTS (SELECT, UPDATE, DELETE BANG,...)

--------------------------NEU MUON CAP HET QUYEN HE THONG --> GRANT ALL PRIVILEGES TO C##Admin_QLNV_GROUP08
/--------------------------CAP 1 SO QUYEN HE THONG-----------------------------------
--Cap quyen tao ROLE 
GRANT CREATE ROLE TO ADMIN_GROUP8 WITH ADMIN OPTION;
GRANT ALTER ANY ROLE TO ADMIN_GROUP8 WITH ADMIN OPTION;
GRANT DROP ANY ROLE TO ADMIN_GROUP8 WITH ADMIN OPTION;

--Cap quyen tao USER
GRANT CREATE USER TO ADMIN_GROUP8 WITH ADMIN OPTION;
GRANT ALTER USER TO ADMIN_GROUP8 WITH ADMIN OPTION;
GRANT DROP USER TO ADMIN_GROUP8 WITH ADMIN OPTION;
    
----Cap quyen tao bang
GRANT CREATE ANY TABLE TO ADMIN_GROUP8  WITH ADMIN OPTION;
GRANT ALTER ANY TABLE TO ADMIN_GROUP8  WITH ADMIN OPTION; --CON CHO PHEP ALTER VIEW
GRANT DROP ANY TABLE TO ADMIN_GROUP8 WITH ADMIN OPTION; -- CHO PHEP DROP TABLE CUA SCHEMA KHAC

 -- WHERE GRANTEE='ADMIN_QLNVGROUP08';
----Cap quyen thu tuc
GRANT CREATE ANY PROCEDURE TO ADMIN_GROUP8 WITH ADMIN OPTION; 
GRANT ALTER ANY PROCEDURE TO ADMIN_GROUP8 WITH ADMIN OPTION; -- QUYEN NAY CON CHO PHEP CHINH SUA FUNCTION 
GRANT EXECUTE ANY PROCEDURE TO ADMIN_GROUP8 WITH ADMIN OPTION;
GRANT DROP ANY PROCEDURE TO ADMIN_GROUP8 WITH ADMIN OPTION; -- QUYEN NAY CON CHO PHEP DROP FUNCTION 


----De tao trigger tren bat ky schema/ bang (schema.[ten bang])
GRANT CREATE ANY TRIGGER TO ADMIN_GROUP8 WITH ADMIN OPTION;
GRANT ALTER ANY TRIGGER TO ADMIN_GROUP8 WITH ADMIN OPTION;
GRANT DROP ANY TRIGGER TO ADMIN_GROUP8 WITH ADMIN OPTION;



----De tao view
GRANT CREATE ANY VIEW TO ADMIN_GROUP8 WITH ADMIN OPTION;
GRANT DROP ANY VIEW TO ADMIN_GROUP8 WITH ADMIN OPTION;

--De tao trigger tren DB va xoa trigg? cua schema khac
GRANT ADMINISTER DATABASE TRIGGER TO ADMIN_GROUP8;




